[package]
name = "lightning-invoice"
version = "0.1.0"
authors = ["Sebastian Geisler <sgeisler@wh2.tu-dresden.de>"]
license = "Apache-2.0"

[dependencies]
bech32 = "0.5.0"
regex = "0.2"
secp256k1 = "0.10"
bitcoin = "0.13"
num-traits = "0.2"